const $=id=>document.getElementById(id);
let csrf='';
const interval=14*86400000;
let updateDates={};
function showCountdowns(){for(const [id,label] of [['cc-countdown','CC list'],['accepted-countdown','Accepted CC list']]){const element=$(id),value=id==='cc-countdown'?updateDates.cc:updateDates.accepted,updated=Date.parse(value),due=updated+interval,left=due-Date.now(),overdue=!value||left<=0,days=value?Math.ceil(Math.abs(left)/86400000):0;const number=document.createElement('span');number.className='countdown-number';number.textContent=overdue?'!':days;const title=document.createElement('strong');title.textContent=overdue?`${label} update due`:`day${days===1?'':'s'} remaining`;const detail=document.createElement('small');detail.textContent=value?(overdue?`${label} is ${days} day${days===1?'':'s'} overdue.`:`${label} due ${new Date(due).toLocaleDateString()}.`):`${label} has not been uploaded yet.`;element.replaceChildren(number,title,detail);element.classList.toggle('overdue',overdue);}}
function showHeaderCountdowns(){for(const [kind,label] of [['cc','CC list'],['accepted','Accepted CC list']]){const element=document.querySelector(`[data-header-countdown="${kind}"]`),value=updateDates[kind],due=Date.parse(value)+interval,left=due-Date.now(),amount=Math.abs(left),days=Math.floor(amount/86400000),hours=Math.floor(amount%86400000/3600000);element.textContent=!value?`${label}: upload needed now.`:left>0?`${label}: ${days} days ${hours} hours until update (${new Date(due).toLocaleDateString()}).`:`${label}: ${days} days ${hours} hours overdue. Update now.`;element.classList.toggle('overdue',!value||left<=0);}}
function download(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csv(rows){return rows.map(r=>r.map(v=>'"'+String(typeof v==='string'&&/^[=+@\-\t\r]/.test(v)?"'"+v:v).replaceAll('"','""')+'"').join(',')).join('\r\n');}

function showBatches(data){$('batches').replaceChildren();const batchKey='early-cc-uploaded-'+data.batch_key;let uploaded;try{uploaded=new Set(JSON.parse(localStorage.getItem(batchKey)||'[]'));}catch{uploaded=new Set();}const restore=document.createElement('button');restore.textContent='Show uploaded batches';restore.className='secondary';restore.onclick=()=>{for(const row of $('batches').querySelectorAll('.campaign-batch'))row.hidden=false;restore.hidden=true;};restore.hidden=uploaded.size===0;$('batches').append(restore);for(let i=0;i<data.campaign_ids.length;i+=5000){const ids=data.campaign_ids.slice(i,i+5000),n=i/5000+1;const box=document.createElement('p');box.className='campaign-batch';box.hidden=uploaded.has(n);const label=document.createElement('label');label.className='check';const check=document.createElement('input');check.type='checkbox';check.checked=uploaded.has(n);check.setAttribute('aria-label',`Batch ${n} uploaded`);label.append(check,'Uploaded');box.append(label);check.onchange=()=>{if(check.checked)uploaded.add(n);else uploaded.delete(n);try{localStorage.setItem(batchKey,JSON.stringify([...uploaded]));box.hidden=check.checked;restore.hidden=uploaded.size===0;}catch{if(check.checked)uploaded.delete(n);else uploaded.add(n);check.checked=!check.checked;$('status').textContent='Could not save batch progress. Allow browser storage and try again.';}};const batchTitle=document.createElement("span");batchTitle.className="batch-title";batchTitle.textContent=`Batch ${n}: ${ids.length} campaigns`;box.append(batchTitle);for(const [label,action] of [['Copy IDs',async()=>{try{await navigator.clipboard.writeText(ids.join('\n'));$('status').textContent=`Batch ${n} copied.`;}catch{$('status').textContent='Clipboard unavailable. Download the text file instead.';}}],['Download text',()=>download(`cc-batch-${n}.txt`,ids.join('\n'))],['Download CSV',()=>download(`cc-batch-${n}.csv`,csv([['Campaign ID'],...ids.map(id=>[id])]),'text/csv')]]){const b=document.createElement('button');b.textContent=label;b.onclick=action;box.append(b);}$('batches').append(box);}}
async function load(){
 $('refresh').disabled=true;$('status').textContent='Reading your current CC list...';
 try{const response=await fetch('/api/early-cc');const data=await response.json();if(!response.ok)throw Error(data.error||'Could not load campaigns.');
 csrf=data.csrf;updateDates={cc:data.cc_updated_at,accepted:data.accepted_updated_at};showCountdowns();showHeaderCountdowns();showBatches(data);$('status').textContent=`${data.campaign_ids.length.toLocaleString()} campaigns remain to opt into in ${Math.ceil(data.campaign_ids.length/5000)} batches. ${data.accepted_excluded.toLocaleString()} already accepted campaigns were excluded; ${data.accepted_total.toLocaleString()} are saved in accepted history. Start dates after ${data.today}. Using ${data.cc_files} CC files.${data.invalid_dates ? ` ${data.invalid_dates} rows skipped because their start date could not be read.` : ''}`;
 }catch(error){$('status').textContent=error.message;}finally{$('refresh').disabled=false;}
}
async function importAccepted(){const file=$('accepted-file').files[0];if(!file){$('import-status').textContent='Choose an accepted campaigns CSV first.';return;}$('import-accepted').disabled=true;$('import-status').textContent='Adding accepted campaigns...';try{const response=await fetch('/api/early-cc/accepted',{method:'POST',headers:{'Content-Type':'text/csv','X-Research-CSRF':csrf},body:await file.text()});const data=await response.json();if(!response.ok)throw Error(data.error||'Could not import accepted campaigns.');$('import-status').textContent=`Added ${data.added.toLocaleString()} new campaign IDs. ${data.accepted_total.toLocaleString()} total are now saved.`;$('accepted-file').value='';await load();}catch(error){$('import-status').textContent=error.message;}finally{$('import-accepted').disabled=false;}}
async function importDeals(){const file=$('deals-file').files[0];if(!file){$('deals-status').textContent='Choose a Deals CSV first.';return;}if(file.size>512*1024*1024){$('deals-status').textContent='Please use a CSV smaller than 512 MB.';return;}$('import-deals').disabled=true;$('deals-status').textContent='Matching deals against the current CC list...';try{const response=await fetch('/api/prime-match',{method:'POST',headers:{'Content-Type':'text/csv','X-Research-CSRF':csrf},body:file});const data=await response.json();if(!response.ok)throw Error(data.error||'Could not process the Deals CSV.');const link=document.createElement('a');link.href='/prime-match.html';link.textContent='Open full Sales prep results';$('deals-status').replaceChildren(document.createTextNode(`${data.rows.length.toLocaleString()} qualifying ASINs and ${data.campaign_ids.length.toLocaleString()} campaigns saved. `),link);$('deals-file').value='';}catch(error){$('deals-status').textContent=error.message;}finally{$('import-deals').disabled=false;}}
$('refresh').onclick=load;$('import-accepted').onclick=importAccepted;$('import-deals').onclick=importDeals;setInterval(()=>{showCountdowns();showHeaderCountdowns();},60000);load();
