const $=id=>document.getElementById(id);
function download(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csv(rows){return rows.map(r=>r.map(v=>'"'+String(typeof v==='string'&&/^[=+@\-\t\r]/.test(v)?"'"+v:v).replaceAll('"','""')+'"').join(',')).join('\r\n');}

function showBatches(data){$('batches').replaceChildren();const batchKey='early-cc-uploaded-'+data.batch_key;let uploaded;try{uploaded=new Set(JSON.parse(localStorage.getItem(batchKey)||'[]'));}catch{uploaded=new Set();}const restore=document.createElement('button');restore.textContent='Show uploaded batches';restore.className='secondary';restore.onclick=()=>{for(const row of $('batches').querySelectorAll('.campaign-batch'))row.hidden=false;restore.hidden=true;};restore.hidden=uploaded.size===0;$('batches').append(restore);for(let i=0;i<data.campaign_ids.length;i+=5000){const ids=data.campaign_ids.slice(i,i+5000),n=i/5000+1;const box=document.createElement('p');box.className='campaign-batch';box.hidden=uploaded.has(n);const label=document.createElement('label');label.className='check';const check=document.createElement('input');check.type='checkbox';check.checked=uploaded.has(n);check.setAttribute('aria-label',`Batch ${n} uploaded`);label.append(check,'Uploaded');box.append(label);check.onchange=()=>{if(check.checked)uploaded.add(n);else uploaded.delete(n);try{localStorage.setItem(batchKey,JSON.stringify([...uploaded]));box.hidden=check.checked;restore.hidden=uploaded.size===0;}catch{if(check.checked)uploaded.delete(n);else uploaded.add(n);check.checked=!check.checked;$('status').textContent='Could not save batch progress. Allow browser storage and try again.';}};const batchTitle=document.createElement("span");batchTitle.className="batch-title";batchTitle.textContent=`Batch ${n}: ${ids.length} campaigns`;box.append(batchTitle);for(const [label,action] of [['Copy IDs',async()=>{try{await navigator.clipboard.writeText(ids.join('\n'));$('status').textContent=`Batch ${n} copied.`;}catch{$('status').textContent='Clipboard unavailable. Download the text file instead.';}}],['Download text',()=>download(`cc-batch-${n}.txt`,ids.join('\n'))],['Download CSV',()=>download(`cc-batch-${n}.csv`,csv([['Campaign ID'],...ids.map(id=>[id])]),'text/csv')]]){const b=document.createElement('button');b.textContent=label;b.onclick=action;box.append(b);}$('batches').append(box);}}
async function load(){
 $('refresh').disabled=true;$('status').textContent='Reading your current CC list...';
 try{const response=await fetch('/api/early-cc');const data=await response.json();if(!response.ok)throw Error(data.error||'Could not load campaigns.');
 showBatches(data);$('status').textContent=`${data.campaign_ids.length.toLocaleString()} upcoming campaigns in ${Math.ceil(data.campaign_ids.length/5000)} batches. Start dates after ${data.today}. Using ${data.cc_files} CC files.${data.invalid_dates ? ` ${data.invalid_dates} rows skipped because their start date could not be read.` : ''}`;
 }catch(error){$('status').textContent=error.message;}finally{$('refresh').disabled=false;}
}
$('refresh').onclick=load;load();
