const $=id=>document.getElementById(id);let result;
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function download(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csv(rows){return rows.map(r=>r.map(v=>'"'+String(typeof v==='string'&&/^[=+@\-\t\r]/.test(v)?"'"+v:v).replaceAll('"','""')+'"').join(',')).join('\r\n');}
function sorted(){return [...result.rows].sort((a,b)=>a[$('sort').value]-b[$('sort').value]||a.asin.localeCompare(b.asin));}
function render(){$('rows').innerHTML=sorted().slice(0,200).map(r=>`<tr><td><a href="https://www.amazon.com/dp/${r.asin}" target="_blank" rel="noopener">${r.asin}</a><br>${esc(r.title)}</td><td>$${r.event_price.toFixed(2)}</td><td>$${r.ytd_low.toFixed(2)}</td><td>${r.vs_ytd_pct.toFixed(2)}%</td><td>${r.campaign_ids.length}</td></tr>`).join('');}
$('match').onclick=async()=>{const f=$('file').files[0];if(!f){$('status').textContent='Choose your deals CSV first.';return;}if(f.size>512*1024*1024){$('status').textContent='Please use a CSV smaller than 512 MB.';return;}$('match').disabled=true;$('results').hidden=true;$('status').textContent='Comparing with the CC CSV list. This may take a minute...';try{const settings=await fetch('/api/settings').then(r=>r.json());const response=await fetch('/api/prime-match',{method:'POST',headers:{'Content-Type':'text/csv','X-Research-CSRF':settings.csrf},body:f});const data=await response.json();if(!response.ok)throw Error(data.error);showResult(data);}catch(e){$('status').textContent=e.message;}finally{$('match').disabled=false;}};
$('sort').onchange=render;$('asins').onclick=()=>download('qualified-asins.txt',sorted().map(r=>r.asin).join('\n'));
$('csv').onclick=()=>download('prime-cc-matches.csv',csv([['ASIN','Product','Event price','YTD low','Percent versus YTD low','Campaign IDs','Event starts','Event ends'],...sorted().map(r=>[r.asin,r.title,r.event_price,r.ytd_low,r.vs_ytd_pct.toFixed(2),r.campaign_ids.join(' '),r.start,r.end])]),'text/csv');

function showResult(data){result=data;$('results').hidden=false;$('status').textContent=`${data.rows.length} qualifying ASINs; ${data.campaign_ids.length} unique campaigns. ${data.invalid_rows} rows missing valid prices/ASIN; ${data.above_limit} rows above the price limit; ${data.not_in_cc} price-qualified ASINs absent from CC.`;$('source').textContent=`CC source on this PC: ${data.cc_files} files; ${data.cc_replacement?'completed replacement batch':'previous list (no completed replacement loaded)'}. Latest file: ${data.cc_source}`;$('batches').replaceChildren();const batchKey='sales-prep-uploaded-'+(data.saved_at||data.cc_source);let uploaded;try{uploaded=new Set(JSON.parse(localStorage.getItem(batchKey)||'[]'));}catch{uploaded=new Set();}const restore=document.createElement('button');restore.textContent='Show uploaded batches';restore.className='secondary';restore.onclick=()=>{for(const row of $('batches').querySelectorAll('.campaign-batch'))row.hidden=false;restore.hidden=true;};restore.hidden=uploaded.size===0;$('batches').append(restore);for(let i=0;i<data.campaign_ids.length;i+=5000){const ids=data.campaign_ids.slice(i,i+5000),n=i/5000+1;const box=document.createElement('p');box.className='campaign-batch';box.hidden=uploaded.has(n);const label=document.createElement('label');label.className='check';const check=document.createElement('input');check.type='checkbox';check.checked=uploaded.has(n);check.setAttribute('aria-label',`Batch ${n} uploaded`);label.append(check,'Uploaded');box.append(label);check.onchange=()=>{if(check.checked)uploaded.add(n);else uploaded.delete(n);try{localStorage.setItem(batchKey,JSON.stringify([...uploaded]));box.hidden=check.checked;restore.hidden=uploaded.size===0;}catch{if(check.checked)uploaded.delete(n);else uploaded.add(n);check.checked=!check.checked;$('status').textContent='Could not save batch progress. Allow browser storage and try again.';}};box.append(`Batch ${n}: ${ids.length} campaigns `);for(const [label,action] of [['Copy IDs',async()=>{try{await navigator.clipboard.writeText(ids.join('\n'));$('status').textContent=`Batch ${n} copied.`;}catch{$('status').textContent='Clipboard unavailable. Download the text file instead.';}}],['Download text',()=>download(`cc-batch-${n}.txt`,ids.join('\n'))],['Download CSV',()=>download(`cc-batch-${n}.csv`,csv([['Campaign ID'],...ids.map(id=>[id])]),'text/csv')]]){const b=document.createElement('button');b.textContent=label;b.onclick=action;box.append(b);}$('batches').append(box);}render();if(data.saved_at)$('source').textContent+=' Saved on this PC: '+new Date(data.saved_at).toLocaleString()+'.';}
$('match').disabled=true;
fetch('/api/prime-match').then(async r=>{if(!r.ok)throw Error('Could not load saved results. Reload to try again.');const data=await r.json();if(data)showResult(data);}).catch(e=>{$('status').textContent=e.message;}).finally(()=>{$('match').disabled=false;});
