const $=id=>document.getElementById(id);let result;let matchPage=0;
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function download(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csv(rows){return rows.map(r=>r.map(v=>'"'+String(typeof v==='string'&&/^[=+@\-\t\r]/.test(v)?"'"+v:v).replaceAll('"','""')+'"').join(',')).join('\r\n');}
function sorted(){
 const key=$('sort').value, direction=$('sort-direction').value==='desc'?-1:1;
 const value=row=>key==='campaign_count'?row.campaign_ids.length:row[key];
 return [...result.rows].sort((a,b)=>{const av=value(a),bv=value(b);const order=typeof av==='string'?av.localeCompare(bv):av-bv;return direction*order||a.asin.localeCompare(b.asin);});
}
function render(){$('match-page').textContent=`Page ${matchPage+1} of ${Math.max(1,Math.ceil(result.rows.length/200))}`;$('match-prev').disabled=matchPage===0;$('match-next').disabled=(matchPage+1)*200>=result.rows.length;document.querySelectorAll('th[data-sort]').forEach(th=>th.setAttribute('aria-sort',th.dataset.sort===$('sort').value?($('sort-direction').value==='asc'?'ascending':'descending'):'none'));$('rows').innerHTML=sorted().slice(matchPage*200,(matchPage+1)*200).map(r=>`<tr><td><a href="https://www.amazon.com/dp/${r.asin}" target="_blank" rel="noopener">${r.asin}</a><br>${esc(r.title)}</td><td>$${r.event_price.toFixed(2)}</td><td>$${r.ytd_low.toFixed(2)}</td><td>${r.vs_ytd_pct.toFixed(2)}%</td><td>${r.campaign_ids.length}</td></tr>`).join('');}
$('sort').onchange=()=>{matchPage=0;render();};$('asins').onclick=()=>download('qualified-asins.txt',sorted().map(r=>r.asin).join('\n'));
$('csv').onclick=()=>download('prime-cc-matches.csv',csv([['ASIN','Product','Event price','YTD low','Percent versus YTD low','Campaign IDs','Event starts','Event ends'],...sorted().map(r=>[r.asin,r.title,r.event_price,r.ytd_low,r.vs_ytd_pct.toFixed(2),r.campaign_ids.join(' '),r.start,r.end])]),'text/csv');

function showResult(data){result=data;$('results').hidden=false;$('status').textContent=`${data.rows.length} qualifying ASINs; ${data.campaign_ids.length} campaigns to opt into; ${data.accepted_excluded||0} already accepted campaigns excluded. ${data.invalid_rows} rows missing valid prices/ASIN; ${data.above_limit} rows above the price limit; ${data.not_in_cc} price-qualified ASINs absent from CC.`;$('source').textContent=`CC source on this PC: ${data.cc_files} files; ${data.cc_replacement?'completed replacement batch':'previous list (no completed replacement loaded)'}. Latest file: ${data.cc_source}`;$('batches').replaceChildren();const batchKey='sales-prep-uploaded-'+(data.batch_key||data.saved_at||data.cc_source);let uploaded;try{uploaded=new Set(JSON.parse(localStorage.getItem(batchKey)||'[]'));}catch{uploaded=new Set();}const restore=document.createElement('button');restore.textContent='Show uploaded batches';restore.className='secondary';restore.onclick=()=>{for(const row of $('batches').querySelectorAll('.campaign-batch'))row.hidden=false;restore.hidden=true;};restore.hidden=uploaded.size===0;$('batches').append(restore);for(let i=0;i<data.campaign_ids.length;i+=5000){const ids=data.campaign_ids.slice(i,i+5000),n=i/5000+1;const box=document.createElement('p');box.className='campaign-batch';box.hidden=uploaded.has(n);const label=document.createElement('label');label.className='check';const check=document.createElement('input');check.type='checkbox';check.checked=uploaded.has(n);check.setAttribute('aria-label',`Batch ${n} uploaded`);label.append(check,'Uploaded');box.append(label);check.onchange=()=>{if(check.checked)uploaded.add(n);else uploaded.delete(n);try{localStorage.setItem(batchKey,JSON.stringify([...uploaded]));box.hidden=check.checked;restore.hidden=uploaded.size===0;}catch{if(check.checked)uploaded.delete(n);else uploaded.add(n);check.checked=!check.checked;$('status').textContent='Could not save batch progress. Allow browser storage and try again.';}};const batchTitle=document.createElement("span");batchTitle.className="batch-title";batchTitle.textContent=`Batch ${n}: ${ids.length} campaigns`;box.append(batchTitle);for(const [label,action] of [['Copy IDs',async()=>{try{await navigator.clipboard.writeText(ids.join('\n'));$('status').textContent=`Batch ${n} copied.`;}catch{$('status').textContent='Clipboard unavailable. Download the text file instead.';}}],['Download text',()=>download(`cc-batch-${n}.txt`,ids.join('\n'))],['Download CSV',()=>download(`cc-batch-${n}.csv`,csv([['Campaign ID'],...ids.map(id=>[id])]),'text/csv')]]){const b=document.createElement('button');b.textContent=label;b.onclick=action;box.append(b);}$('batches').append(box);}render();if(data.saved_at)$('source').textContent+=' Saved on this PC: '+new Date(data.saved_at).toLocaleString()+'.';}
async function loadMatches(){ $('status').textContent='Updating matches from the current lists...';try{const response=await fetch('/api/prime-match');const data=await response.json();if(!response.ok)throw Error(data.error||'Could not load matches');matchPage=0;if(data)showResult(data);else $('status').textContent='Upload a Deals CSV on CSV uploads to get started.';}catch(e){$('status').textContent=e.message;}}
$('reload-sales').onclick=()=>{loadMatches();loadAll();};loadMatches();
$('match-prev').onclick=()=>{matchPage--;render();};$('match-next').onclick=()=>{matchPage++;render();};
$('sort-direction').onchange=()=>{if(result)render();};
document.querySelectorAll('th[data-sort]').forEach(th=>th.querySelector('button').onclick=()=>{
 if($('sort').value===th.dataset.sort)$('sort-direction').value=$('sort-direction').value==='asc'?'desc':'asc';
 else{$('sort').value=th.dataset.sort;$('sort-direction').value='asc';}
 if(result)render();
});

let allOffset=0,allSort='asin',allDirection='asc',allRequest=0;
let excluded=[];try{excluded=JSON.parse(localStorage.getItem('sales-hidden-categories')||'[]');}catch{}
async function loadAll(){const request=++allRequest;$('all-count').textContent='Loading deals...';try{
 const query=new URLSearchParams({offset:allOffset,sort:allSort,direction:allDirection,exclude:JSON.stringify(excluded)});
 const response=await fetch('/api/sales-catalog?'+query);const data=await response.json();if(!response.ok)throw Error(data.error||'Could not load deals');if(request!==allRequest)return;
 $('all-count').textContent=data.total?`${allOffset+1}–${Math.min(allOffset+100,data.total)} of ${data.total.toLocaleString()} deals`:'No deals to display';
 $('all-prev').disabled=allOffset===0;$('all-next').disabled=allOffset+100>=data.total;
 $('all-head').replaceChildren();const tr=document.createElement('tr');for(const name of data.headers){const th=document.createElement('th'),button=document.createElement('button');button.className='column-sort';button.textContent=name;th.setAttribute('aria-sort',name===allSort?(allDirection==='asc'?'ascending':'descending'):'none');button.onclick=()=>{allDirection=allSort===name&&allDirection==='asc'?'desc':'asc';allSort=name;allOffset=0;loadAll();};th.append(button);tr.append(th);}$('all-head').append(tr);
 $('all-body').replaceChildren();for(const row of data.rows){const tr=document.createElement('tr');for(const value of row){const td=document.createElement('td');td.textContent=value;tr.append(td);}$('all-body').append(tr);}
 $('deal-categories').replaceChildren();for(const category of data.categories){const label=document.createElement('label');label.className='check';const box=document.createElement('input');box.type='checkbox';box.value=category;box.checked=excluded.includes(category);label.append(box,category||'(Uncategorized)');$('deal-categories').append(label);}
 }catch(e){if(request===allRequest)$('all-count').textContent=e.message;}}
$('apply-categories').onclick=()=>{excluded=[...$('deal-categories').querySelectorAll('input:checked')].map(x=>x.value);try{localStorage.setItem('sales-hidden-categories',JSON.stringify(excluded));}catch{}allOffset=0;loadAll();};
$('all-prev').onclick=()=>{allOffset=Math.max(0,allOffset-100);loadAll();};$('all-next').onclick=()=>{allOffset+=100;loadAll();};loadAll();
