'use strict';
const $=id=>document.getElementById(id);
const sections={feed:'Opportunity Feed',cc:'Creator Connection',low:'Low Competition',trending:'Trending Products',launch:'Launch Sniper',seasonal:'Seasonal Opportunities',deals:'Deals / Open Box',shortlist:'Shortlist',outreach:'Outreach Queue',film:'Film Queue',published:'Published Products',settings:'Settings / Scoring Rules'};
let config,csrf,stages,view='feed',page=1,selected,requestNumber=0;
const esc=v=>String(v??'Unknown').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const value=v=>v==null?'Unknown':typeof v==='boolean'?(v?'Yes':'No'):typeof v==='number'?v.toLocaleString(undefined,{maximumFractionDigits:2}):String(v);
const money=v=>v==null?'Unknown':'$'+Number(v).toFixed(2);
const pct=v=>v==null?'Unknown':Number(v).toFixed(1)+'%';
async function api(path,data){const r=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json','X-Research-CSRF':csrf},body:JSON.stringify(data)}:{});const body=await r.json();if(!r.ok)throw Error(body.error||'Request failed');return body;}
function fail(e){$('message').textContent=e.message;}
function defaults(){const f=$('filters');HTMLFormElement.prototype.reset.call(f);for(const [key,v] of Object.entries(config.filters)){const el=f.elements.namedItem(key);if(el)el.type==='checkbox'?el.checked=Boolean(v):el.value=Array.isArray(v)?v.join(', '):v??'';}page=1;}
function params(){const q=new URLSearchParams(new FormData($('filters')));for(const el of $('filters').querySelectorAll('input[type=checkbox]'))q.set(el.name,String(el.checked));q.set('view',view);q.set('page',page);q.set('sort',$('sort').value);q.set('direction',$('direction').value);return q;}
async function load(){const ticket=++requestNumber;$('message').textContent='Loading saved products…';try{const q=params();$('export').href='/api/export?'+q;const data=await api('/api/products?'+q);if(ticket!==requestNumber)return;$('message').textContent='';$('count').textContent=data.total.toLocaleString()+' matching products';$('page').textContent=`Page ${data.page} of ${Math.max(1,Math.ceil(data.total/data.size))}`;$('previous').disabled=page<=1;$('next').disabled=page*data.size>=data.total;$('empty').hidden=data.total>0;const current=$('categories').value;$('categories').innerHTML='<option value="">All categories</option>'+data.categories.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');$('categories').value=current;
$('rows').innerHTML=data.rows.map(r=>`<tr><td><div class="product">${r.image?`<img src="${esc(r.image)}" alt="" loading="lazy">`:''}<div><button data-asin="${esc(r.asin)}">${esc(r.title||r.asin)}</button><small>${esc(r.asin)} · ${esc(r.brand)}</small></div></div></td><td><span class="badge ${r.film_score>=80?'strong':r.film_score>=50?'possible':''}">${value(r.film_score)}</span><small>${value(r.score_coverage)}% coverage</small></td><td>${money(r.price)}</td><td>${value(r.monthly_sold)}</td><td>${pct(r.growth)}<small>${esc(r.sales_trend_direction)}</small></td><td>${pct(r.commission)}<small>${r.cc_active?'Active':'Inactive / Unknown'}</small></td><td>${money(r.estimated_commission_per_sale)}</td><td>${value(r.influencer_videos)}</td><td>${value(r.merchant_video)}</td><td>${value(r.total_videos)}</td><td>${value(r.bsr)}</td><td>${pct(r.bsr90)}</td><td>${esc(r.category)}</td><td><button class="secondary" data-asin="${esc(r.asin)}">${esc(r.shortlist?.status||'Save / review')}</button></td></tr>`).join('');}catch(e){if(ticket===requestNumber)fail(e);}}
function field(label,v){return `<div><dt>${esc(label)}</dt><dd>${esc(value(v))}</dd></div>`;}
async function detail(asin){try{selected=await api('/api/products/'+encodeURIComponent(asin));const r=selected;$('detail-title').textContent=r.title||r.asin;const metrics=[['ASIN',r.asin],['Brand',r.brand],['Category',r.category],['Subcategory',r.subcategory],['Price',money(r.price)],['30-day average price',money(r.price_avg30)],['90-day average price',money(r.price_avg90)],['Monthly sales (lower bound)',r.monthly_sold],['90-day average monthly sales',r.monthly_sold_90],['Sales growth',pct(r.growth)],['Sales direction',r.sales_trend_direction],['Current BSR',r.bsr],['30-day average BSR',r.bsr_avg30],['90-day average BSR',r.bsr_avg90],['30-day BSR improvement',pct(r.bsr30)],['90-day BSR improvement',pct(r.bsr90)],['Rating',r.rating],['Reviews',r.review_count],['Observed variants',r.variant_count],['Observed sellers',r.seller_count],['Merchant video',r.merchant_video],['Merchant videos',r.merchant_video_count],['Influencer videos',r.influencer_videos],['Observed total videos',r.total_videos],['Video source',r.video_count_source],['Video confidence',r.video_count_confidence],['Video checked',r.video_count_last_checked?new Date(r.video_count_last_checked*1000).toLocaleString():null],['Active CC',r.cc_active],['Commission',pct(r.commission)],['Est. CC per sale',money(r.estimated_commission_per_sale)],['Campaign ends',r.campaign_end],['Keepa updated',r.keepa_last_updated?new Date(r.keepa_last_updated*1000).toLocaleString():null]];
$('detail-content').innerHTML=`${r.image?`<img class="detail-image" src="${esc(r.image)}" alt="Product">`:''}<p><a href="${esc(r.amazon_url)}" target="_blank" rel="noopener noreferrer">View on Amazon ↗</a></p><dl>${metrics.map(x=>field(...x)).join('')}</dl><h3>Film score ${value(r.film_score)} / 100 · Evidence coverage ${value(r.score_coverage)}%</h3><dl>${Object.entries(r.score_components).map(([k,v])=>field(k.replaceAll('_',' '),v.points==null?'Unknown':`${v.points} / ${v.maximum}`)).join('')}</dl><details><summary>All Creator Connection campaigns (${r.campaigns.length})</summary><pre>${esc(JSON.stringify(r.campaigns,null,2))}</pre></details><details><summary>Data sources and historical data</summary><pre>${esc(JSON.stringify({sources:r.sources,history:r.history??'Unknown'},null,2))}</pre></details>`;
const s=r.shortlist||{status:'Researching',priority:'Normal'};const fields=[['priority','Priority','select',['Low','Normal','High']],['status','Status','select',stages],['purchase_price','Purchase cost','number'],['sample_requested','Sample requested','checkbox'],['brand_contacted','Brand contacted','checkbox'],['product_ordered','Product ordered','checkbox'],['contact_date','Contact date','date'],['contact_method','Contact method','text'],['response_status','Response','select',['Not contacted','Contacted','Waiting','Accepted','Declined','No response']],['followup_date','Follow-up date','date'],['date_acquired','Acquired','date'],['date_filmed','Filmed','date'],['date_uploaded','Uploaded','date'],['video_url','Amazon video URL','url']];
$('shortlist-fields').innerHTML=fields.map(([key,label,type,choices])=>`<label>${label}${type==='select'?`<select name="${key}">${choices.map(c=>`<option ${s[key]===c?'selected':''}>${esc(c)}</option>`).join('')}</select>`:`<input name="${key}" type="${type}" ${type==='checkbox'?(s[key]?'checked':''):`value="${esc(s[key]??'')}"`} ${type==='number'?'min="0" step="0.01"':''}>`}</label>`).join('');$('shortlist-form').elements.notes.value=s.notes||'';$('saved-status').textContent=s.date_added?'Added '+new Date(s.date_added*1000).toLocaleDateString():'';if(!$('detail').open)$('detail').showModal();}catch(e){fail(e);}}
function navigate(next){view=next;page=1;$('view-title').textContent=sections[view];for(const b of $('navigation').children)b.classList.toggle('active',b.dataset.view===view);const future=['launch','seasonal','deals'].includes(view);$('research-view').hidden=future||view==='settings';$('settings-view').hidden=view!=='settings';$('future-view').hidden=!future;$('export').hidden=future||view==='settings';if(view==='settings')$('configuration').value=JSON.stringify(config,null,2);else if(!future)load();}
$('navigation').innerHTML=Object.entries(sections).map(([id,label])=>`<button data-view="${id}">${label}</button>`).join('');$('navigation').addEventListener('click',e=>{if(e.target.dataset.view)navigate(e.target.dataset.view);});$('filters').onsubmit=e=>{e.preventDefault();page=1;load();};$('reset').onclick=()=>{defaults();load();};for(const id of ['sort','direction'])$(id).onchange=()=>{page=1;load();};$('previous').onclick=()=>{page--;load();};$('next').onclick=()=>{page++;load();};$('rows').onclick=e=>{const b=e.target.closest('[data-asin]');if(b)detail(b.dataset.asin);};$('close-detail').onclick=()=>$('detail').close();$('shortlist-form').onsubmit=async e=>{e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f));for(const el of f.querySelectorAll('[type=checkbox]'))d[el.name]=el.checked;d.purchase_price=d.purchase_price===''?null:Number(d.purchase_price);try{await api('/api/shortlist/'+encodeURIComponent(selected.asin),d);$('saved-status').textContent='Saved on this PC';load();}catch(error){$('saved-status').textContent=error.message;}};$('settings-form').onsubmit=async e=>{e.preventDefault();try{const next=JSON.parse($('configuration').value);await api('/api/settings',next);config=next;defaults();$('message').textContent='Settings saved and scores recalculated.';}catch(error){fail(error);}};
api('/api/settings').then(data=>{config=data.config;csrf=data.csrf;stages=data.stages;defaults();navigate('feed');}).catch(fail);
